### ISSUE TITLE
docker preview messes up current dir

### ISSUE THREAD

**Issue by KlavsKlavsen** [goodbaikin/VSC-Org-Preview#9]
it really should change workingdir to /tmp/org-mode.tmp or something - so the files ending in .bbl, dvi, pdf and .tex aren't in CWD.

**Comment by goodbaikin** [comment]
I'm sorry I left it for a long time.
I edited init.el to move the output directory to /tmp/org-mode.tmp and pushed the new image.
I just also uploaded the files to [this repository](https://github.com/goodbaikin/org2pdf) so you can see the details.
